version: '3.8'
services:
  stats-db:
    image: postgres:14-alpine
    ports:
      - "6590:5432"
    environment:
      - POSTGRES_DB=ewm_stat_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  main-db:
    image: postgres:14-alpine
    ports:
      - "6580:5432"
    environment:
      - POSTGRES_DB=ewm_main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


  main-server:
    build: ./main-server
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SERVER_PORT=8080
      - STATS-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm_main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-server:
    build: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stat_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - SERVER-PORT=9090
